### get orders by customer id
GET http://localhost:8080/api/orders/1


### create an order
POST localhost:8080/api/orders
Content-Type: application/json

{
  "customerId": 1,
  "products": [
    {"productId": 2, "quantity": 6},
    {"productId": 1, "quantity": 2}
  ]
}

### get the order items by order id
GET http://localhost:8080/api/orders/items/200001