### get product by id
GET http://localhost:8080/api/products/1

### get the most ordered products
GET http://localhost:8080/api/products/top/3

### create new product
POST http://localhost:8080/api/products
Content-Type: application/json

{
  "name": "testProduct",
  "description": "description for test product",
  "price": 99.99,
  "stockQuantity": 100,
  "supplierName": "Polar Electronics Oy",
  "categoryNames": [
    "Elektroniikka"
  ]
}

### lock a product by id or unlock the product
PATCH http://localhost:8080/api/products/1/toggle-lock

### increase all products by giving percetange
PATCH http://localhost:8080/api/products/price?percentageIncrease=1

